# Generated by Django 4.2.6 on 2023-10-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="sesion",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("token", models.CharField(default="", max_length=200)),
            ],
        ),
    ]
