# Generated by Django 4.2.6 on 2023-10-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ClinicaJmaesMichaelApp",
            "0002_administrador_asistencia_doctores_enfermeras_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="procedimiento",
            old_name="nmbreProcedimiento",
            new_name="nombreProcedimientos",
        ),
        migrations.RemoveField(
            model_name="procedimiento",
            name="ordenProc",
        ),
        migrations.AddField(
            model_name="procedimiento",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="asistencia",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ayudadiagnostica",
            name="ordenAyud",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="medicamentos",
            name="ordenMed",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="ordenes",
            name="orden",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
