# Generated by Django 4.2.6 on 2023-10-22 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "ClinicaJmaesMichaelApp",
            "0003_rename_nmbreprocedimiento_procedimiento_nombreprocedimiento_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ayudadiagnostica",
            name="orden",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ClinicaJmaesMichaelApp.ordenes",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medicamentos",
            name="orden",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ClinicaJmaesMichaelApp.ordenes",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="procedimiento",
            name="orden",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ClinicaJmaesMichaelApp.ordenes",
            ),
            preserve_default=False,
        ),
    ]
