# Generated by Django 4.2.6 on 2023-10-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ClinicaJmaesMichaelApp",
            "0004_ayudadiagnostica_orden_medicamentos_orden_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ayudadiagnostica",
            name="especialista",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="procedimiento",
            name="especialista",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
